### ISSUE TITLE
Test fails with Time.new

### ISSUE THREAD

**Issue by gd875** [learn-co-curriculum/rack-responses-lab#5]
The tests only work if the app gets the time using Time.now (allowing the test to use the time from the spec instead of the current time). It fails if using Time.new because the test will use the system's current time. System time can only be morning or afternoon—so one of the tests will fail.

**Comment by curiositypaths** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
