### ISSUE TITLE
Possible Rspec bug, Using Time.new.hour vs Time.now.hour

### ISSUE THREAD

**Issue by byojelly** [learn-co-curriculum/rack-responses-lab#6]
The code below works in this lab to pass all test cases.  However, when initially setting up my instance variable current_time, i used current_time = Time.new.hour   .    This code did not pass the good afternon rspec.   To my knowledge, .now is an alias of .new so both should work?  If not what should i take into consideration to distinguish why .now is to be used.

Thank you

class Application

  def call(env)
    resp = Rack::Response.new  
    current_time = Time.now.hour      #initially i used .new, however, if i used .now, the code works
    if current_time > 12
        resp.write "Afternoon\n"
      else
        resp.write "Morning\n"
    end
    resp.finish
  end
end

**Comment by mkirby** [comment]
This seems to still be a slight issue several years later. Is there any update that could be added to the rspec test to have both Time.new and Time.now pass? If not I would suggest that the read me for this lesson include a note about how to call Time and which variation to use to pass the test.
