### ISSUE TITLE
Tests would not pass

### ISSUE THREAD

**Issue by dapawn** [learn-co-curriculum/rack-responses-lab#7]
I had to make a change to the tests to set the time, the tests were always using the current time:

```
    allow(Time).to receive(:now).and_return(Time.utc(*[26, 10, 10, 2, 1, 2018, 1, 154, false, "MST"]))
  #  allow(Time).to receive(:now){
  #    Time.new(2015,11,27,9,30)
  #  }
```

**Comment by curiositypaths** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
